respa/urls.py
from django.urls import path, re_path
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static
from helusers import admin
from django.views.generic.base import RedirectView

from resources.api import RespaAPIRouter
from resources.views.images import ResourceImageView
from resources.views.ical import ICalFeedView

admin.autodiscover()

if getattr(settings, 'RESPA_COMMENTS_ENABLED', False):
    import comments.api

if getattr(settings, 'RESPA_CATERINGS_ENABLED', False):
    import caterings.api

router = RespaAPIRouter()

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ra/', include('respa_admin.urls', namespace='respa_admin')),
    path('i18n/', include('django.conf.urls.i18n')),
    path('accounts/', include('allauth.urls')),
    path('grappelli/', include('grappelli.urls')),
    path('resource_image/<int:pk>', ResourceImageView.as_view(), name='resource-image-view'),
    path('v1/', include(router.urls)),
    re_path(r'v1/reservation/ical/(?P<ical_token>[-\w\d]+).ics$', ICalFeedView.as_view(), name='ical-feed'),
    path('', RedirectView.as_view(url='v1/')),
]

if 'reports' in settings.INSTALLED_APPS:
    from reports.api import DailyReservationsReport, ReservationDetailsReport
    urlpatterns.extend([
        path('reports/daily_reservations/', DailyReservationsReport.as_view(), name='daily-reservations-report'),
        path('reports/reservation_details/', ReservationDetailsReport.as_view(), name='reservation-details-report'),
    ])


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

respa_admin/urls.py
from django.conf.urls import url as unauthorized_url
from django.urls import include

from . import views
from .views.resources import (
    ResourceListView,
    SaveResourceView
)
from .auth import admin_url as url

app_name = 'respa_admin'
urlpatterns = [
    url(r'^$', ResourceListView.as_view(), name='index'),
    unauthorized_url(r'^login/$', views.LoginView.as_view(), name='login'),
    unauthorized_url(r'^login/tunnistamo/$',
                     views.tunnistamo_login, name='tunnistamo-login'),
    unauthorized_url(r'^logout/$', views.logout, name='logout'),
    url(r'^resources/$', ResourceListView.as_view(), name='resources'),
    url(r'^resource/new/$', SaveResourceView.as_view(), name='new-resource'),
    url(r'^resource/edit/(?P<resource_id>\w+)/$', SaveResourceView.as_view(), name='edit-resource'),
    url(r'^i18n/$', include('django.conf.urls.i18n'), name='language'),
]

respa_admin/views/_login.py
from urllib.parse import urlencode

from django.conf import settings
from django.contrib import auth as django_auth
from django.http import HttpResponseBadRequest, HttpResponseRedirect
from django.urls import reverse
from django.views.generic.base import TemplateView
from helusers.providers.helsinki.views import HelsinkiOAuth2Adapter

from ..auth import is_allowed_user


class LoginView(TemplateView):
    template_name = "respa_admin/login.html"

    def get_context_data(self, login_failed=False, **kwargs):
        request = self.request
        user = request.user

        context = super().get_context_data(**kwargs)

        if _is_authenticated(user) and not is_allowed_user(user):
            context['not_allowed_user'] = True
        if login_failed:
            context['login_failed'] = True
        context['tunnistamo_login_url'] = _get_url_with_next(
            request, 'respa_admin:tunnistamo-login')
        context['show_login_form'] = self._allow_username_login()

        return context

    def post(self, request, *args, **kwargs):
        if not self._allow_username_login():
            return HttpResponseBadRequest("Username login not allowed")

        post_data = self.request.POST

        user = django_auth.authenticate(
            self.request,
            username=post_data.get('username'),
            password=post_data.get('password'))

        if not user:
            context = self.get_context_data(login_failed=True)
            return self.render_to_response(context)

        django_auth.login(self.request, user)

        next_url = self.request.GET.get('next', reverse('respa_admin:index'))
        return HttpResponseRedirect(next_url)

    def _allow_username_login(self):
        return getattr(settings, 'RESPA_ADMIN_USERNAME_LOGIN', False)


def tunnistamo_login(request):
    if _is_authenticated(request.user):
        # If user is already logged in with unallowed account, then log
        # out first, to allow re-login with another account.
        if not is_allowed_user(request.user):
            return _logout_locally_and_in_tunnistamo(request)

    url = _get_url_with_next(request, 'helsinki_login')
    return HttpResponseRedirect(url)


def _is_authenticated(user):
    return bool(user and user.is_authenticated)


def _get_url_with_next(request, url_name):
    url = reverse(url_name)
    next_url = request.GET.get('next', None)
    next_part = ('?' + urlencode({'next': next_url})) if next_url else ''
    return url + next_part


def logout(request):
    index_uri = reverse('respa_admin:index')
    return _logout_locally_and_in_tunnistamo(request, redirect_uri=index_uri)


def _logout_locally_and_in_tunnistamo(request, redirect_uri=None):
    """
    Log out locally and in Tunnistamo.

    :type request: django.http.HttpRequest
    """
    # First logout locally
    django_auth.logout(request)

    # Then logout from Tunnistamo with a redirect which points
    # back to this view with a given next parameter
    tunnistamo_url = HelsinkiOAuth2Adapter.profile_url.replace('/user/', '')
    next_param = urlencode({
        'next': request.build_absolute_uri(redirect_uri)
    })
    return HttpResponseRedirect(tunnistamo_url + '/logout/?' + next_param)

respa_admin/views/base.py
from django.conf import settings


class ExtraContextMixin():
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['INSTRUCTIONS_URL'] = settings.RESPA_ADMIN_INSTRUCTIONS_URL
        return context

respa_admin/views/resources.py
from django.conf import settings
from django.contrib import messages
from django.db.models import FieldDoesNotExist
from django.http import HttpResponseRedirect
from django.template.response import TemplateResponse
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView
from django.utils.translation import ugettext_lazy as _
from respa_admin.views.base import ExtraContextMixin

from resources.models import (
    Resource,
    Period,
    Day,
    ResourceImage,
    ResourceType,
    Unit,
)
from respa_admin import forms

from respa_admin.forms import (
    get_period_formset,
    get_resource_image_formset,
    ResourceForm,
)

from respa_admin import accessibility_api


class ResourceListView(ExtraContextMixin, ListView):
    model = Resource
    paginate_by = 10
    context_object_name = 'resources'
    template_name = 'respa_admin/page_resources.html'

    def get(self, request, *args, **kwargs):
        get_params = request.GET
        self.search_query = get_params.get('search_query')
        self.resource_type = get_params.get('resource_type')
        self.resource_unit = get_params.get('resource_unit')
        self.order_by = get_params.get('order_by')
        return super().get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(ResourceListView, self).get_context_data()
        resources = self.get_unfiltered_queryset()
        context['types'] = ResourceType.objects.filter(
            pk__in=resources.values('type'))
        context['units'] = Unit.objects.filter(
            pk__in=resources.values('unit'))
        context['search_query'] = self.search_query
        context['selected_resource_type'] = self.resource_type or ''
        context['selected_resource_unit'] = self.resource_unit or ''
        context['order_by'] = self.order_by or ''
        return context

    def get_unfiltered_queryset(self):
        qs = super(ResourceListView, self).get_queryset()
        qs = qs.modifiable_by(self.request.user)
        return qs

    def get_queryset(self):
        qs = self.get_unfiltered_queryset()

        if self.search_query:
            qs = qs.filter(name__icontains=self.search_query)
        if self.resource_type:
            qs = qs.filter(type=self.resource_type)
        if self.resource_unit:
            qs = qs.filter(unit=self.resource_unit)
        if self.order_by:
            order_by_param = self.order_by.strip('-')
            try:
                if Resource._meta.get_field(order_by_param):
                    qs = qs.order_by(self.order_by)
            except FieldDoesNotExist:
                qs = self.get_unfiltered_queryset()

        qs = qs.prefetch_related('images', 'unit')

        return qs


class RespaAdminIndex(ResourceListView):
    paginate_by = 7
    template_name = 'respa_admin/index.html'


def admin_office(request):
    return TemplateResponse(request, 'respa_admin/page_office.html')


class SaveResourceView(ExtraContextMixin, CreateView):
    """
    View for saving new resources and updating existing resources.
    """
    http_method_names = ['get', 'post']
    model = Resource
    pk_url_kwarg = 'resource_id'
    form_class = ResourceForm
    template_name = 'respa_admin/resources/create_resource.html'

    def get_context_data(self, **kwargs):
        context = super(SaveResourceView, self).get_context_data(**kwargs)
        if settings.RESPA_ADMIN_VIEW_RESOURCE_URL and self.object.id:
            context['RESPA_ADMIN_VIEW_RESOURCE_URL'] = settings.RESPA_ADMIN_VIEW_RESOURCE_URL + self.object.id
        else:
            context['RESPA_ADMIN_VIEW_RESOURCE_URL'] = ''
        return context

    def get_queryset(self):
        qs = super().get_queryset()
        return qs.modifiable_by(self.request.user)

    def get_success_url(self, **kwargs):
        messages.success(self.request, 'Resurssi tallennettu')
        return reverse_lazy('respa_admin:edit-resource', kwargs={
            self.pk_url_kwarg: self.object.id,
        })

    def get(self, request, *args, **kwargs):
        if self.pk_url_kwarg in kwargs:
            self.object = self.get_object()
            page_headline = _('Edit resource')
        else:
            page_headline = _('Create new resource')
            self.object = None

        form = self.get_form()

        period_formset_with_days = get_period_formset(
            self.request,
            instance=self.object,
        )

        resource_image_formset = get_resource_image_formset(
            self.request,
            instance=self.object,
        )

        trans_fields = forms.get_translated_field_count(resource_image_formset)

        accessibility_data_link = self._get_accessibility_data_link(request)

        return self.render_to_response(
            self.get_context_data(
                accessibility_data_link=accessibility_data_link,
                form=form,
                period_formset_with_days=period_formset_with_days,
                resource_image_formset=resource_image_formset,
                trans_fields=trans_fields,
                page_headline=page_headline,
            )
        )

    def _get_accessibility_data_link(self, request):
        if self.object is None or self.object.unit is None or not self.object.unit.is_admin(request.user):
            return None
        if self.object.type.id not in getattr(settings, 'RESPA_ADMIN_ACCESSIBILITY_VISIBILITY', []):
            return None
        if not getattr(settings, 'RESPA_ADMIN_ACCESSIBILITY_API_SECRET', None):
            return None
        api_url = getattr(settings, 'RESPA_ADMIN_ACCESSIBILITY_API_BASE_URL', '')
        system_id = getattr(settings, 'RESPA_ADMIN_ACCESSIBILITY_API_SYSTEM_ID', '')
        secret = getattr(settings, 'RESPA_ADMIN_ACCESSIBILITY_API_SECRET', '')
        target_id = self.object.pk
        target_name = self.object.name
        user = request.user.email or request.user.username
        return accessibility_api.generate_url(
            api_url,
            system_id,
            target_id,
            target_name,
            user,
            secret,
        )

    def post(self, request, *args, **kwargs):
        if self.pk_url_kwarg in kwargs:
            self.object = self.get_object()
        else:
            self.object = None

        form = self.get_form()

        period_formset_with_days = get_period_formset(request=request, instance=self.object)
        resource_image_formset = get_resource_image_formset(request=request, instance=self.object)

        if self._validate_forms(form, period_formset_with_days, resource_image_formset):
            return self.forms_valid(form, period_formset_with_days, resource_image_formset)
        else:
            return self.forms_invalid(form, period_formset_with_days, resource_image_formset)

    def get_form(self, form_class=None):
        form = super().get_form(form_class)
        unit_field = form.fields['unit']
        unit_field.queryset = unit_field.queryset.managed_by(self.request.user)
        unit_field.required = True
        if self.object and self.object.pk:
            unit_field.disabled = True
        return form

    def forms_valid(self, form, period_formset_with_days, resource_image_formset):
        self.object = form.save()

        self._delete_extra_periods_days(period_formset_with_days)
        period_formset_with_days.instance = self.object
        period_formset_with_days.save()

        self._save_resource_purposes()
        self._delete_extra_images(resource_image_formset)
        self._save_resource_images(resource_image_formset)
        self.object.update_opening_hours()

        return HttpResponseRedirect(self.get_success_url())

    def forms_invalid(self, form, period_formset_with_days, resource_image_formset):
        messages.error(self.request, 'Tallennus epäonnistui. Tarkista lomakkeen virheet.')

        # Extra forms are not added upon post so they
        # need to be added manually below. This is because
        # the front-end uses the empty 'extra' forms for cloning.
        temp_image_formset = get_resource_image_formset()
        temp_period_formset = get_period_formset()
        temp_day_form = temp_period_formset.forms[0].days.forms[0]

        resource_image_formset.forms.append(temp_image_formset.forms[0])
        period_formset_with_days.forms.append(temp_period_formset.forms[0])

        # Add a nested empty day to each period as well.
        for period in period_formset_with_days:
            period.days.forms.append(temp_day_form)

        trans_fields = forms.get_translated_field_count(resource_image_formset)

        return self.render_to_response(
            self.get_context_data(
                form=form,
                period_formset_with_days=period_formset_with_days,
                resource_image_formset=resource_image_formset,
                trans_fields=trans_fields,
                page_headline=_('Edit resource'),
            )
        )

    def _validate_forms(self, form, period_formset, image_formset):
        valid_form = form.is_valid()
        valid_period_form = period_formset.is_valid()
        valid_image_formset = image_formset.is_valid()

        return valid_form and valid_period_form and valid_image_formset

    def _save_resource_purposes(self):
        checked_purposes = self.request.POST.getlist('purposes')

        for purpose in checked_purposes:
            self.object.purposes.add(purpose)

    def _save_resource_images(self, resource_image_formset):
        count = len(resource_image_formset)

        for i in range(count):
            resource_image = resource_image_formset.forms[i].save(commit=False)
            resource_image.resource = self.object
            image_key = 'images-' + str(i) + '-image'

            if image_key in self.request.FILES:
                resource_image.image = self.request.FILES[image_key]

            resource_image.save()

respa_admin/templates/respa_admin/_base.html
{% load staticfiles %}
{% load i18n %}
{% get_available_languages as LANGUAGES %}
{% get_current_language as LANGUAGE_CODE %}

<!DOCTYPE html>

<html lang="{{ LANGUAGE_CODE }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Respa Admin - {% block page_title %}{% endblock page_title %}</title>
    <meta name="description" content=""/>
    <meta name="author" content=""/>
    <link rel="author" href="humans.txt"/>
    <link rel="stylesheet" type="text/css" href="{% static 'respa_admin/main.css' %}">

</head>

<body>
    {% block body_content %}

    <div class="hidden" id="all-languages">
        {% for key, value in LANGUAGES %}
            <data value="{{ key }}"></data>
        {% endfor %}
    </div>

    <div class='header'>
        {% include "respa_admin/_nav.html" %}

        {% if messages %}
            {% include "respa_admin/common/_notification.html" %}
        {% endif %}

        {% block form_nav %}

        {% endblock form_nav %}
    </div>

    <main class='content'>
        {% block koro_shape %}

        {% endblock koro_shape %}


        {% block body %}

        {% endblock body %}
    </main>

    <div class="footer">
        {% block footer %}

        {% endblock footer %}
    </div>

    {% endblock body_content %}

    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="{% static 'respa_admin/styles-bundle.js' %}"></script>
    <script type="text/javascript" src="{% static 'respa_admin/base-bundle.js' %}"></script>
    {% block js_extra %}
    {% endblock js_extra %}
</body>

</html>

respa_admin/templates/respa_admin/_user_matrix.html
<div class="grey">
    <section>
        <div class="container">
            <div class="matrix-title">
                <div class="col-sm-11">
                    <h4>#toimipisteen# käyttöoikeudet</h4>
                </div>
                <div class="col-sm-2 button-wrapper">
                    <a href="#" class="btn btn-primary inverse small-text align-middle">
                        <span class='glyphicon glyphicon-plus icon-left' aria-hidden="true"></span> Lisää käyttäjä
                    </a>
                </div>
            </div>
            <div class="user-matrix">
                <div class="table-wrapper">
                    <div class="table-big">
                        <p class="table-title-user pointer">
                            Käyttäjä <span class='icon-right glyphicon glyphicon-sort' aria-hidden="true"></span>
                        </p>
                    </div>
                    <div class="table-small">
                        <p class="table-title">
                            Voi lisätä käyttäjiä
                        </p>
                    </div>
                    <div class="table-small">
                        <p class="table-title">
                            Voi hyväksyä varauksia
                        </p>
                    </div>
                    <div class="table-small">
                        <p class="table-title">
                            Voi nähdä pääsykoodin
                        </p>
                    </div>
                    <div class="table-small">
                        <p class="table-title">
                            Voi muuttaa käyttöoikeuksia
                        </p>
                    </div>
                    <div class="table-small">
                        <p class="table-title">
                            Voi poistaa käyttäjän
                        </p>
                    </div>
                    <div class="table-medium"></div>
                </div>
                {% for i in "1234" %}
                    <div class="table-wrapper">
                        <div class="table-big">
                            <p class="table-small-text pad-left">
                                konsta.kutvonen@helsinki.fi
                            </p>
                        </div>
                        {% for j in "12345" %}
                            {% with template=i|add:'id'|add:j %}
                            <div class="table-small">
                                <div class="custom-checkbox">
                                  <input class="checkbox-custom" id={{ template }} type="checkbox">
                                  <label class="checkbox-custom-label" for={{ template }}></label>
                                </div>
                            </div>
                            {% endwith %}
                        {% endfor %}
                        <div class="table-medium pointer">
                            <p class="table-small-text">
                                <span class='icon-left glyphicon glyphicon-minus' aria-hidden="true"></span> Poista
                            </p>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </section>
</div>

respa_admin/templates/respa_admin/index.html
{% extends "respa_admin/_base.html" %}

{% block koro_shape %}
    <section class="hero-section bg-light">
        <div class="container">
            {% include "./common/_notification.html" with text="Welcome #user#" %}
            <div>
                <h2>Toimipaikat</h2>
                <div class='row cards-list'>
                    {% for i in "123" %}
                    <div class="col-sm-4">
                        <div class="card">
                            <div class="card-body">
                                <h5 class="card-title">Why Do I have to Pay?</h5>
                                <p class="card-text">With <a href="#">supporting</a> text below as a natural lead-in to additional content.</p>
                                <a href="#" class="btn btn-primary">
                                    Katso tilat<span class='glyphicon glyphicon-menu-right icon-right' aria-hidden="true"></span>
                                </a>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
                <div class="container-fluid">
                    <div class="resource-control">
                        <a class="btn" href="#">
                            <span class="glyphicon glyphicon-plus-sign icon-left" aria-hidden="true"></span>
                            Lisää uusi resurssit <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                        </a>
                        <a class="btn" href="#">
                            <span class="glyphicon glyphicon-plus-sign icon-left" aria-hidden="true"></span>
                            Lisää uusi toimipaikka <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock koro_shape %}

{% block body %}
    {% include "respa_admin/resources/_resource_list.html" %}
{% endblock body %}

respa_admin/templates/respa_admin/login.html
{% extends "respa_admin/_base.html" %}
{% load i18n %}

{% block page_title %}{% trans "Log in" %}{% endblock page_title %}

{% block body_content %}
<main>
    <section class="hero-section bg-light">
        <div class="container">
            <h1 class="h2">Respa Admin</h1>

            {% if not_allowed_user %}
            <p class="panel panel-default noti error">
                {% trans "You are not allowed to use Respa Admin." %}
            </p>
            <p class="panel-default">
                {% blocktrans %}
                Sorry, but "{{ user }}" is not allowed to use Respa Admin.
                Please log in with a different account.
                {% endblocktrans %}
            </p>
            {% endif %}

            {% if login_failed %}
            <p class="panel panel-default noti error">
                {% trans "Login failed" %}
            </p>
            {% endif %}

            <h2 class="h3">{% trans "Log in" %}</h2>

            {% if tunnistamo_login_url %}
            <hr>
            <a
                href="{{ tunnistamo_login_url }}"
                class="btn btn-primary"
                type="button"
            >
                {% trans "Log in with Helsinki account" %}
            </a>
            {% endif %}

            {% if show_login_form %}
            <hr>
            <form method="post">
                {% csrf_token %}
                <div class="form-group">
                    <label for="username">
                        {% trans "Username" %}
                    </label>
                    <input
                        type="text"
                        id="username" name="username"
                        class="form-control"
                    >
                </div>
                <div class="form-group">
                    <label for="password">
                        {% trans "Password" %}
                    </label>
                    <input
                        type="password"
                        id="password" name="password"
                        class="form-control"
                    >
                </div>
                <button type="submit" class="btn btn-primary">
                    {% trans "Log in" %}
                </button>
            </form>
            {% endif %}

            <hr>
        </div>
    </section>
</main>
{% endblock %}

respa_admin/templates/respa_admin/page_office.html
{% extends "respa_admin/_base.html" %}

{% block koro_shape %}
    <section class="hero-section bg-light">
        <div class="container">
            <div class="info row">
                <div class="col-sm-8">
                    <h2>Toimipaikan nimi</h2>
                    <p>
                        Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Sed posuere interdum sem. Quisque ligula eros ullamcorper quis, lacinia quis facilisis sed sapien. Mauris varius diam vitae arcu. Sed arcu lectus auctor vitae, consectetuer et venenatis eget velit. Sed augue orci, lacinia eu tincidunt et eleifend nec lacus. Donec ultricies nisl ut felis, suspendisse potenti. Lorem ipsum ligula ut hendrerit mollis, ipsum erat vehicula risus, eu suscipit sem libero nec erat. Aliquam erat volutpat. Sed congue augue vitae neque. Nulla consectetuer porttitor pede. Fusce purus morbi tortor magna condimentum vel, placerat id blandit sit amet tortor.
                    </p>
                    <span><b>Osoite: </b> Mannerheimintie 1, 00200 Helsinki </span>
                </div>
                <div class="col-sm-4 col-info">
                    <div class="panel panel-default text-center info-details">
                        <div class="general-info">
                            <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
                            <small>Toimipaikan ylläpitäjä</small>
                        </div>
                        <strong>Etunimi Sukunimi</strong>
                        <small>etunimi.sukunimi@hel.fi</small>
                        <span>040 1234 567</span>
                    </div>
                </div>
            </div>
            <div class="container-fluid">
                <div class="resource-control">
                    <a class="btn" href="#">
                        <span class="glyphicon glyphicon-plus-sign icon-left" aria-hidden="true"></span>
                        Lisää uusi resurssit tähän toimipaikkaan <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                    </a>
                    <a class="btn" href="#">
                        <span class="glyphicon glyphicon-pencil icon-left" aria-hidden="true"></span>
                        Muokkaa toimipaikkaa <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                    </a>
                    <a class="btn" href="#">
                        <span class="glyphicon glyphicon-pencil icon-left" aria-hidden="true"></span>
                        Muokkaa käyttöoikeuksia <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                    </a>
                </div>
            </div>
        </div>
    </section>
{% endblock koro_shape %}

{% block body %}
    {% include "respa_admin/resources/_resource_list.html" %}
    {% include "respa_admin/_user_matrix.html" %}
{% endblock body %}

respa_admin/templates/respa_admin/page_resources.html
{% extends "respa_admin/_base.html" %}
{% load staticfiles %}
{% load i18n %}

{% block koro_shape %}
    <section class="hero-section bg-light">
        <div class="container">
            <div class="headline">
                <div class="resources-report row">
                    <h1 class="col-sm-6">{% trans 'All resources I manage' %}</h1>
                    <span class="col-sm-6 resources-count">{{ paginator.count }} kpl</span>
                </div>
                <a class="btn resource-control" href="{% url 'respa_admin:new-resource' %}">
                    <span class="glyphicon glyphicon-plus-sign icon-left" aria-hidden="true"></span>
                    {% trans 'Add a new resource' %}<span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                </a>
                <form action="." method="get">
                    <div class="form-group resources-search center-block">
                        <div class="input-group">
                            <span class="input-group-addon">{% trans 'Search' %}</span>
                            <input autofocus type="text" class="form-control text-input" name="search_query" value="{{ request.GET.search_query }}">
                            <span class="input-group-btn">
                                <button class="btn btn-default" type="submit">
                                    <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
                                </button>
                            </span>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </section>
{% endblock koro_shape %}

{% block body %}
    {% include "respa_admin/resources/_resource_list.html" %}
{% endblock body %}